name: Playwright E2E Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or the version you use locally
    - name: Install dependencies
      run: npm install
    - name: Install browsers
      run: npx playwright install
    - name: Run tests
      run: npm test # or your specific test command
