jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: study-brew
      - name: Build
        run: npm run build
        working-directory: study-brew
      - name: Run tests
        run: npm test
        working-directory: study-brew
  